apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: promotions-ingress
  labels:
    app: promotions
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: promotions.localdev.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: promotions
            port:
              number: 8080