apiVersion: v1
kind: Service
metadata:
  name: promotions-service
  labels:
    app: promotions
spec:
  selector:
    app: promotions
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
