# PostgreSQL Credentials Secret
# This secret can also be created from the command line:
#
# export POSTGRES_PASSWORD='pgs3cr3t'
# export DATABASE_URI='postgresql+psycopg://postgres:pgs3cr3t@postgres:5432/promotions'
#
# kubectl create secret generic postgres-creds \
#     --from-literal=password=$POSTGRES_PASSWORD \
#     --from-literal=database_uri=$DATABASE_URI
#
# Base64 values:
# password: cGdzM2NyM3Q= (pgs3cr3t)
# database_uri: cG9zdGdyZXNxbCtwc3ljb3BnOi8vcG9zdGdyZXM6cGdzM2NyM3RAcG9zdGdyZXM6NTQzMi9wcm9tb3Rpb25z
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  labels:
    app: postgres
type: Opaque
data:
  password: cGdzM2NyM3Q=
  database_uri: cG9zdGdyZXNxbCtwc3ljb3BnOi8vcG9zdGdyZXM6cGdzM2NyM3RAcG9zdGdyZXM6NTQzMi9wcm9tb3Rpb25z
